### ISSUE TITLE
instances[0] - IndexError: list index out of range

### ISSUE THREAD

**Issue by ccaudle** [FrostyX/tracer#100]
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 47, in exclude_types
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 46, in <lambda>
    applications = filter(lambda app: app.type not in app_types, self)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 202, in type
    elif self.is_session:
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 194, in is_session
    if re.search('ssh-.*-session', str(self.name)):
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 272, in name
    Id = bus.get_unit_property_from_pid(self.instances[0].pid,'Id')
IndexError: list index out of range

**Comment by Wrecknor** [comment]
/usr/lib64/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 38, in with_helpers
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 37, in <lambda>
    applications = filter(lambda app: app.helper, self)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 217, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 120, in _helper
    if app.type == Applications.TYPES["DAEMON"]:
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 202, in type
    elif self.is_session:
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 194, in is_session
    if re.search('ssh-.*-session', str(self.name)):
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 270, in name
    if self.instances and bus.unit_path_from_pid(self.instances[0].pid):
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 260, in instances
    lambda process: self._attributes["name"] in [process.name(), process.real_name])
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 83, in filtered
    if function(process):
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 260, in <lambda>
    lambda process: self._attributes["name"] in [process.name(), process.real_name])
  File "/usr/lib/python3.6/site-packages/tracer/resources/processes.py", line 73, in name
    return 'ssh-{0}-session'.format(re.split(' |@|',self._attr("cmdline")[0])[1])
IndexError: list index out of range

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

**Comment by sean797** [comment]
@ccaudle Traceback is different to @Wrecknor created https://github.com/FrostyX/tracer/issues/109 to track @Wrecknor issue

@ccaudle I think this was caused by our dynamic use of `psutil`, since https://github.com/FrostyX/tracer/commit/08fed6a4a7ee1134c9d464df30308e9e13a706c9 fixed that im going to close that this issue.
