### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by shcherbak** [FrostyX/tracer#104]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 29, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 31, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by abitrolly** [comment]
The same error again.

[tracer.log](https://github.com/FrostyX/tracer/files/1865191/tracer.log)

**Comment by abitrolly** [comment]
I can only guess that some applications don't have `helper` field.
