### ISSUE TITLE
tracer stand-alone crashes with error KeyError: 'ID_LIKE'

### ISSUE THREAD

**Issue by pdvnl** [FrostyX/tracer#105]
On F27 I installed python3-dnf-plugin-tracer.

executing 'tracer' outside dnf gives this error:

```
[root@fedora ~]# tracer
Traceback (most recent call last):
  File "/usr/bin/tracer", line 34, in <module>
    tracer.main.run()
  File "/usr/lib/python3.6/site-packages/tracer/main.py", line 45, in run
    return router.dispatch()
  File "/usr/lib/python3.6/site-packages/tracer/resources/router.py", line 52, in dispatch
    controller = DefaultController(self.args, self.packages)
  File "/usr/lib/python3.6/site-packages/tracer/controllers/default.py", line 50, in __init__
    System.package_manager(erased=args.erased),
  File "/usr/lib/python3.6/site-packages/tracer/resources/system.py", line 88, in package_manager
    distro = System.distribution()
  File "/usr/lib/python3.6/site-packages/tracer/resources/system.py", line 56, in distribution
    if os_release_data["ID_LIKE"]:
KeyError: 'ID_LIKE'
```

**Comment by sean797** [comment]
@pdvnl I cannot reproduce this on F27? Can I see a copy of your `/etc/os-release` file ?

**Comment by pdvnl** [comment]
```
cat /etc/os-release
NAME=Generic
VERSION="27 (Generic)"
ID=generic
VERSION_ID=27
PRETTY_NAME="Generic 27 (Generic)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:generic:generic:27"
HOME_URL="http://www.zombo.com/"
SUPPORT_URL="https://en.wikipedia.org/wiki/Help!_(album)"
BUG_REPORT_URL="https://youtu.be/CSemARaqGqE"
REDHAT_BUGZILLA_PRODUCT="Generic"
REDHAT_BUGZILLA_PRODUCT_VERSION=%{bug_version}
REDHAT_SUPPORT_PRODUCT="Generic"
REDHAT_SUPPORT_PRODUCT_VERSION=%{bug_version}
PRIVACY_POLICY_URL="http://nsa.gov"
```

**Comment by pdvnl** [comment]
See my comments on the [commit](https://github.com/FrostyX/tracer/commit/558f1a2a14dcbd9c13c6f48cc17258584fc37353).

**Comment by sean797** [comment]
@pdvnl that is not a standard `/etc/os-release` file from Fedora. I don't know how or why your `/etc/os-release` looks like that but it should be something like this for Fedora 27 (this example is Fedora workstation)

```
NAME=Fedora
VERSION="27 (Workstation Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**Comment by pdvnl** [comment]
I must admit that the contents of my /etc/os-release surprised me too. But this is a very old VM upgrade since ages.

after replace by your version the output of tracer is now:

```
/usr/lib64/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)
You should restart:
  * Some applications using:
      systemctl restart rsyslog

Additionally to those process above, there are:
  - 1 processes requiring reboot
```

Is this - with the warning - as expected?

**Comment by pdvnl** [comment]
> This is definitelly not a Fedora os-release. Can you check the output of rpm -qf /etc/os-release It should be
> "fedora-release-27-something". I guess that someone/something overwrote this file.

```
# rpm -qf /etc/os-release
generic-release-27-2.fc27.noarch
```

**Comment by sean797** [comment]
I think your issue is https://bugzilla.redhat.com/show_bug.cgi?id=1568050
