### ISSUE TITLE
Upgrade F27 --> F28 hung with tracer, stacktrace on restart

### ISSUE THREAD

**Issue by abitrolly** [FrostyX/tracer#110]
Upgrade process from Fedora 27 to Fedora 28 stalled for 4 hours. After rebooting upgrade seemed to be successful, but there is a stacktrace from tracer in `journalctl -b -1`
```
May 02 10:36:26 blackred dnf[636]: DEBUG:dnf.plugin:Completion plugin: Generating completion cache...
May 02 10:36:26 blackred dnf[636]:  
May 02 10:36:26 blackred dnf[636]: Tracer:
May 02 10:36:26 blackred dnf[636]:  Call to Tracer API ended unexpectedly:
May 02 10:36:26 blackred dnf[636]: Traceback (most recent call last):
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
May 02 10:36:26 blackred dnf[636]:     tracer.render()
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
May 02 10:36:26 blackred dnf[636]:     return view.render()
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 74, in render
May 02 10:36:26 blackred dnf[636]:     blocks.append({"content": note_content()})
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 53, in note_content
May 02 10:36:26 blackred dnf[636]:     view.assign("session_count", self.args.applications.count_type(Applications.TYPES["SESSION"]))
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 64, in count_type
May 02 10:36:26 blackred dnf[636]:     if application.type == app_type:
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 202, in type
May 02 10:36:26 blackred dnf[636]:     elif self.is_session:
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 194, in is_session
May 02 10:36:26 blackred dnf[636]:     if re.search('ssh-.*-session', str(self.name)):
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 270, in name
May 02 10:36:26 blackred dnf[636]:     bus = SystemdDbus()
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib/python3.6/site-packages/tracer/resources/SystemdDbus.py", line 22, in __init__
May 02 10:36:26 blackred dnf[636]:     self.__systemd = dbus.SystemBus().get_object('org.freedesktop.systemd1','/org/freedesktop/systemd1')
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
May 02 10:36:26 blackred dnf[636]:     follow_name_owner_changes=follow_name_owner_changes)
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
May 02 10:36:26 blackred dnf[636]:     self._named_service = conn.activate_name_owner(bus_name)
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
May 02 10:36:26 blackred dnf[636]:     return self.get_name_owner(bus_name)
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
May 02 10:36:26 blackred dnf[636]:     's', (bus_name,), **keywords)
May 02 10:36:26 blackred dnf[636]:   File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
May 02 10:36:26 blackred dnf[636]:     message, timeout)
May 02 10:36:26 blackred dnf[636]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Disconnected: Connection is closed
May 02 10:36:26 blackred dnf[636]: Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
May 02 10:36:26 blackred dnf[636]: We apologize for any inconvenience
```

I wanted to check if `tracer` is guilty in this delay, but Fedora didn't allow me to login in parallel console with Ctrl+Alt+F2 telling that system is booting up, so no logins. There are also a lot of DBus error messages during this time
```
May 02 06:29:26 blackred dnf[636]:   Verifying        : zsh-5.4.1-2.fc27.x86_64                          4482/4483
May 02 06:29:35 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='
avc:  denied  { send_msg } for msgtype=method_return dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:
s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:30:00 blackred dnf[636]:   Verifying        : zvbi-0.2.35-4.fc27.x86_64                        4483/4483ERROR:dbus.proxies:Introspect error 
on :1.8:/org/freedesktop/systemd1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
May 02 06:30:00 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=error error_name=org.freedesktop.DBus.Error.InvalidArgs dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:30:25 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:30:25 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:30:50 blackred dnf[636]: ERROR:dbus.proxies:Introspect error on :1.8:/org/freedesktop/systemd1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
May 02 06:30:50 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=error error_name=org.freedesktop.DBus.Error.InvalidArgs dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:31:41 blackred dnf[636]: ERROR:dbus.proxies:Introspect error on :1.8:/org/freedesktop/systemd1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
May 02 06:31:41 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=error error_name=org.freedesktop.systemd1.NoSuchUnit dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:32:06 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:32:31 blackred dnf[636]: ERROR:dbus.proxies:Introspect error on :1.8:/org/freedesktop/systemd1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
May 02 06:32:31 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=error error_name=org.freedesktop.DBus.Error.InvalidArgs dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:32:56 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:32:56 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:33:21 blackred dnf[636]: ERROR:dbus.proxies:Introspect error on :1.8:/org/freedesktop/systemd1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
May 02 06:33:21 blackred audit[639]: USER_AVC pid=639 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=error error_name=org.freedesktop.DBus.Error.InvalidArgs dest=:1.21 spid=1 tpid=636 scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:rpm_t:s0 tclass=dbus permissive=0
                                      exe=2F7573722F62696E2F646275732D6461656D6F6E202864656C6574656429 sauid=81 hostname=? addr=? terminal=?'
May 02 06:34:11 blackred dnf[636]: ERROR:dbus.proxies:Introspect error on :1.8:/org/freedesktop/systemd1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

```

**Comment by FrostyX** [comment]
Thank you for the report, sorry it slipped through the cracks.
F27 -> F28 was a long time ago, anyone please reopen if you encounter this in a recent upgrade.
