### ISSUE TITLE
 Call to Tracer API ended unexpectedly:

### ISSUE THREAD

**Issue by sanjayankur31** [FrostyX/tracer#112]
Hi,

A dnf update gave me this:

```
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 45, in with_helpers
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 44, in <lambda>
    applications = filter(lambda app: app.helper, self)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 217, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 122, in _helper
    return "systemctl restart {0}".format(app.name)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 273, in name
    Id = bus.get_unit_property_from_pid(self.instances[0].pid,'Id')
  File "/usr/lib/python3.6/site-packages/tracer/resources/SystemdDbus.py", line 46, in get_unit_property_from_pid
    proxy = dbus.SystemBus().get_object('org.freedesktop.systemd1', self.unit_path_from_pid(pid))
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 244, in __init__
    _dbus_bindings.validate_object_path(object_path)
TypeError: validate_object_path() argument 1 must be str, not bool

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
```
Here is the setup:

```
$ rpm -qa \*tracer\* dnf
python3-tracer-0.7.0-1.fc28.noarch
tracer-common-0.7.0-1.fc28.noarch
traceroute-2.1.0-6.fc28.x86_64
python3-dnf-plugin-tracer-2.0.5-3.fc28.noarch
dnf-2.7.5-12.fc28.noarch
```

**Comment by alfalco** [comment]
Similar situation here:

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

And the setup:

rpm -qa \*tracer\* dnf
traceroute-2.1.0-6.fc28.x86_64
dnf-2.7.5-12.fc28.noarch
tracer-common-0.7.0-1.fc28.noarch
python3-tracer-0.7.0-1.fc28.noarch
python3-dnf-plugin-tracer-2.0.5-3.fc28.noarch

**Comment by sudhirkhanger** [comment]
```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

Full log - https://gist.github.com/sudhirkhanger/80751340d7a47677aba4e233a6f03a6d

**Comment by sean797** [comment]
Note that commit fixes @sanjayankur31 issue, @alfalco & @sudhirkhanger please raise new issues as they are different tracebacks, with different fixes.

Thanks!
