### ISSUE TITLE
TypeError: update() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by sanjayankur31** [FrostyX/tracer#113]
This is the other issue. Just hit it today somehow:

```

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

```

```
$ rpm -qa \*tracer\*
python3-tracer-0.7.0-1.fc28.noarch
traceroute-2.1.0-6.fc28.x86_64
python3-dnf-plugin-tracer-2.0.5-3.fc28.noarch
tracer-common-0.7.0-1.fc28.noarch
```

**Comment by jdavis-douglas-co-us** [comment]
Ditto - Fedora 29 upgrade as of this morning:

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given
