### ISSUE TITLE
 Call to Tracer API ended unexpectedly

### ISSUE THREAD

**Issue by Joseph-Smith** [FrostyX/tracer#120]
Verifying        : python2-unbound-1.8.1-1.fc29.x86_64                                                                                              109/115 
  Verifying        : python3-unbound-1.8.2-1.fc29.x86_64                                                                                              110/115 
  Verifying        : python3-unbound-1.8.1-1.fc29.x86_64                                                                                              111/115 
  Verifying        : unbound-libs-1.8.2-1.fc29.x86_64                                                                                                 112/115 
  Verifying        : unbound-libs-1.8.1-1.fc29.x86_64                                                                                                 113/115 
  Verifying        : vulkan-loader-1.1.92.0-1.fc29.x86_64                                                                                             114/115 
  Verifying        : vulkan-loader-1.1.82.0-1.fc29.x86_64                                                                                             115/115 
Etckeeper plugin: post transaction commit
Completion plugin: Generating completion cache...
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:

**Comment by scudderm** [comment]
I've had the same issue:

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

**Comment by pjoc** [comment]
Me too:
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

**Comment by adatum** [comment]
Same here.

```
Name         : python3-dnf-plugin-tracer
Version      : 4.0.4
Release      : 1.fc30

```

```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

```

**Comment by josephomorrow** [comment]
Same problem here with the same trace info.
