### ISSUE TITLE
TypeError: validate_object_path() argument 1 must be str, not bool

### ISSUE THREAD

**Issue by sanjayankur31** [FrostyX/tracer#122]
```

Tracer:                                                                                                                                                          [24/871]
 Call to Tracer API ended unexpectedly:
                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                      
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction                                                                                
    tracer.render()                                                                                                                                                     
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render                                                                                     
    return view.render()                                                                                                                                                
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render                                                                                   
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},                                                                               
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content                                                                     
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")                                                                          
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 54, in exclude_types                                                                    
    return ApplicationsCollection(applications)                                                                                                                         
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 53, in <lambda>                                                                         
    applications = filter(lambda app: app.type not in app_types, self)                                                                                                  
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 202, in type                                                                           
    elif self.is_session:                                                                                                                                               
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 194, in is_session                                                                     
    if re.search('ssh-.*-session', str(self.name)):                                                                                                                     
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 272, in name
    if not bus.has_service_property_from_pid(self.instances[0].pid,'PAMName'):
  File "/usr/lib/python3.7/site-packages/tracer/resources/SystemdDbus.py", line 39, in has_service_property_from_pid
    proxy = dbus.SystemBus().get_object('org.freedesktop.systemd1', self.unit_path_from_pid(pid))
  File "/usr/lib64/python3.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.7/site-packages/dbus/proxies.py", line 244, in __init__
    _dbus_bindings.validate_object_path(object_path)
TypeError: validate_object_path() argument 1 must be str, not bool

```

python3-tracer-0.7.0-3.fc29.noarch

**Comment by marmalodak** [comment]
I just saw exactly this while install zlib-devel.

**Comment by ohhai** [comment]
It appeared for me as well

dnf-4.4.0-3.fc32.noarch
python3-dnf-plugin-tracer-4.0.12-1.fc32.noarch
python3-3.8.6-1.fc32.x86_64

```
  Verifying        : kernel-modules-extra-5.8.13-200.fc32.x86_64                                                                                                                                                                          76/76
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer.render()
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 91, in render
    return view.render()
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 45, in with_helpers
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 44, in <lambda>
    applications = filter(lambda app: app.helper, self)
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 217, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 126, in _helper
    elif app.type == Applications.TYPES["STATIC"]:
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 204, in type
    elif self.is_service:
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 212, in is_service
    return SystemdDbus().unit_path_from_id("{0}.service".format(self.name))
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 277, in name
    Id = bus.get_unit_property_from_pid(self.instances[0].pid,'Id')
  File "/usr/lib/python3.8/site-packages/tracer/resources/SystemdDbus.py", line 48, in get_unit_property_from_pid
    proxy = dbus.SystemBus().get_object('org.freedesktop.systemd1', self.unit_path_from_pid(pid))
  File "/usr/lib64/python3.8/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib64/python3.8/site-packages/dbus/proxies.py", line 246, in __init__
    _dbus_bindings.validate_object_path(object_path)
TypeError: validate_object_path() argument 1 must be str, not bool

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
  babl-0.1.82-1.fc32.x86_64                clang-10.0.1-3.fc32.x86_64
```
