### ISSUE TITLE
TypeError: update() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by JerryPenguin** [FrostyX/tracer#123]
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

**Comment by tyll** [comment]
I got the same error when trying to do a dnf upgrade from Fedora 29 to 30

**Comment by ydroneaud** [comment]
Happening right now on F30

**Comment by WSLUser** [comment]
I have this on F28

**Comment by adatum** [comment]
I just got this error as well while applying some updates on F30.

**Comment by abitrolly** [comment]
F30.
```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given
```

**Comment by boycottsystemd** [comment]
Fedora 30 package upgrade:
 
```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given
```
