### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by muellerbe** [FrostyX/tracer#124]
dnf upgrade
...
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

you need more information? please give detailed instructions

**Comment by szydell** [comment]
Same issue while dnf update on the rpi3.

**Comment by FrostyX** [comment]
I believe this was fixed in d7f65868 by @sean797, so I am closing the issue. Please feel free to reopen if it occurs again.

**Comment by ohhai** [comment]
Just got something looking like this.

python3-tracer-0.7.4-1.fc32.noarch
dnf-4.4.0-2.fc32.noarch
python3-3.8.6-1.fc32.x86_64

```
  Verifying        : sssd-proxy-2.3.1-2.fc32.x86_64            106/106


Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer.render()
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 91, in render
    return view.render()
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
  gimp-2:2.10.22-2.fc32.x86_64                         gimp-libs-2:2.10.22-2.fc32.x86_64
```

**Comment by ohhai** [comment]
Got it again. Might be related: #104

python3-tracer-0.7.5-1.fc33.noarch
dnf-4.6.1-1.fc33.noarch
python3-3.9.2-1.fc33.x86_64


```
Verifying        : kmod-VirtualBox-5.11.7-200.fc33.x86_64-6.1.18-1.fc33.x86_64                                                                                                         59/59 
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer.render()
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 91, in render
    return view.render()
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
```
