### ISSUE TITLE
TypeError: 'str' object is not callable -- different than #99

### ISSUE THREAD

**Issue by PenelopeFudd** [FrostyX/tracer#125]
```
$ sudo yum install openssl-devel
Last metadata expiration check: 0:32:19 ago on Fri 12 Apr 2019 10:03:38 AM PDT.
Dependencies resolved.
===================================================================================================================================================================================================
 Package                                               Architecture                             Version                                            Repository                                 Size
===================================================================================================================================================================================================
Installing:
 openssl-devel                                         x86_64                                   1:1.1.1b-3.fc29                                    updates                                   2.2 M
Installing dependencies:
 krb5-devel                                            x86_64                                   1.16.1-25.fc29                                     updates                                   437 k
 libcom_err-devel                                      x86_64                                   1.44.4-1.fc29                                      updates                                    16 k
 libkadm5                                              x86_64                                   1.16.1-25.fc29                                     updates                                    75 k
 libselinux-devel                                      x86_64                                   2.8-6.fc29                                         updates                                   117 k
 libsepol-devel                                        x86_64                                   2.8-3.fc29                                         updates                                    45 k
 pcre2-devel                                           x86_64                                   10.32-8.fc29                                       updates                                   601 k
 pcre2-utf32                                           x86_64                                   10.32-8.fc29                                       updates                                   212 k
 keyutils-libs-devel                                   x86_64                                   1.5.10-8.fc29                                      fedora                                     40 k
 libverto-devel                                        x86_64                                   0.3.0-6.fc29                                       fedora                                     15 k

Transaction Summary
===================================================================================================================================================================================================
Install  10 Packages

Total download size: 3.8 M
Installed size: 7.4 M
Is this ok [y/N]: y
Downloading Packages:
(1/10): libcom_err-devel-1.44.4-1.fc29.x86_64.rpm                                                                                                                   29 kB/s |  16 kB     00:00    
(2/10): libkadm5-1.16.1-25.fc29.x86_64.rpm                                                                                                                         130 kB/s |  75 kB     00:00    
(3/10): libsepol-devel-2.8-3.fc29.x86_64.rpm                                                                                                                       384 kB/s |  45 kB     00:00    
(4/10): krb5-devel-1.16.1-25.fc29.x86_64.rpm                                                                                                                       524 kB/s | 437 kB     00:00    
(5/10): libselinux-devel-2.8-6.fc29.x86_64.rpm                                                                                                                     394 kB/s | 117 kB     00:00    
(6/10): pcre2-utf32-10.32-8.fc29.x86_64.rpm                                                                                                                        409 kB/s | 212 kB     00:00    
(7/10): pcre2-devel-10.32-8.fc29.x86_64.rpm                                                                                                                        754 kB/s | 601 kB     00:00    
(8/10): keyutils-libs-devel-1.5.10-8.fc29.x86_64.rpm                                                                                                               144 kB/s |  40 kB     00:00    
(9/10): libverto-devel-0.3.0-6.fc29.x86_64.rpm                                                                                                                      97 kB/s |  15 kB     00:00    
(10/10): openssl-devel-1.1.1b-3.fc29.x86_64.rpm                                                                                                                    1.8 MB/s | 2.2 MB     00:01    
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                              1.5 MB/s | 3.8 MB     00:02     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                           1/1 
  Installing       : libverto-devel-0.3.0-6.fc29.x86_64                                                                                                                                       1/10 
  Installing       : keyutils-libs-devel-1.5.10-8.fc29.x86_64                                                                                                                                 2/10 
  Installing       : pcre2-utf32-10.32-8.fc29.x86_64                                                                                                                                          3/10 
  Installing       : pcre2-devel-10.32-8.fc29.x86_64                                                                                                                                          4/10 
  Installing       : libsepol-devel-2.8-3.fc29.x86_64                                                                                                                                         5/10 
  Installing       : libselinux-devel-2.8-6.fc29.x86_64                                                                                                                                       6/10 
  Installing       : libkadm5-1.16.1-25.fc29.x86_64                                                                                                                                           7/10 
  Installing       : libcom_err-devel-1.44.4-1.fc29.x86_64                                                                                                                                    8/10 
  Installing       : krb5-devel-1.16.1-25.fc29.x86_64                                                                                                                                         9/10 
  Installing       : openssl-devel-1:1.1.1b-3.fc29.x86_64                                                                                                                                    10/10 
  Running scriptlet: openssl-devel-1:1.1.1b-3.fc29.x86_64                                                                                                                                    10/10 
  Verifying        : krb5-devel-1.16.1-25.fc29.x86_64                                                                                                                                         1/10 
  Verifying        : libcom_err-devel-1.44.4-1.fc29.x86_64                                                                                                                                    2/10 
  Verifying        : libkadm5-1.16.1-25.fc29.x86_64                                                                                                                                           3/10 
  Verifying        : libselinux-devel-2.8-6.fc29.x86_64                                                                                                                                       4/10 
  Verifying        : libsepol-devel-2.8-3.fc29.x86_64                                                                                                                                         5/10 
  Verifying        : openssl-devel-1:1.1.1b-3.fc29.x86_64                                                                                                                                     6/10 
  Verifying        : pcre2-devel-10.32-8.fc29.x86_64                                                                                                                                          7/10 
  Verifying        : pcre2-utf32-10.32-8.fc29.x86_64                                                                                                                                          8/10 
  Verifying        : keyutils-libs-devel-1.5.10-8.fc29.x86_64                                                                                                                                 9/10 
  Verifying        : libverto-devel-0.3.0-6.fc29.x86_64                                                                                                                                      10/10 
New leaves:
  openssl-devel.x86_64
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 217, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 120, in _helper
    if app.type == Applications.TYPES["DAEMON"]:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 204, in type
    elif self.is_service:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 212, in is_service
    return SystemdDbus().unit_path_from_id("{0}.service".format(self.name))
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 272, in name
    if not bus.has_service_property_from_pid(self.instances[0].pid,'PAMName'):
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 261, in instances
    lambda process: self._attributes["name"] in [process.name(), process.real_name])
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 90, in filtered
    if function(process):
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 261, in <lambda>
    lambda process: self._attributes["name"] in [process.name(), process.real_name])
  File "/usr/lib/python3.7/site-packages/tracer/resources/processes.py", line 80, in name
    return 'ssh-{0}-session'.format(re.split(' |@',' '.join(self._attr("cmdline")))[1])
IndexError: list index out of range

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Installed:
  openssl-devel-1:1.1.1b-3.fc29.x86_64   krb5-devel-1.16.1-25.fc29.x86_64   libcom_err-devel-1.44.4-1.fc29.x86_64   libkadm5-1.16.1-25.fc29.x86_64             libselinux-devel-2.8-6.fc29.x86_64  
  libsepol-devel-2.8-3.fc29.x86_64       pcre2-devel-10.32-8.fc29.x86_64    pcre2-utf32-10.32-8.fc29.x86_64         keyutils-libs-devel-1.5.10-8.fc29.x86_64   libverto-devel-0.3.0-6.fc29.x86_64  

Complete!
```

**Comment by PenelopeFudd** [comment]
I just did 'sudo yum erase openssl-devel' and then 'sudo yum install openssl-devel', and it worked without error this time.  

It's a pity the stack trace doesn't show the arguments when they're simple, then we could see the string that it was trying to execute.

**Comment by Patron-du** [comment]
I got a similar issue. I ran a dnf update. the following packages were installed: 
kernel-5.0.11-200.fc29.x86_64                             kernel-core-5.0.11-200.fc29.x86_64              
kernel-devel-5.0.11-200.fc29.x86_64                   kernel-modules-5.0.11-200.fc29.x86_64           
kernel-modules-extra-5.0.11-200.fc29.x86_64     libbsd-0.9.1-2.fc29.x86_64                      
python3-simplejson-3.16.0-1.fc29.x86_64.

Error Message:
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
