### ISSUE TITLE
Having problems with Fedora 30 (beta, but to be released within a week)

### ISSUE THREAD

**Issue by businessBoris** [FrostyX/tracer#127]
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

**Comment by adatum** [comment]
See issue https://github.com/FrostyX/tracer/issues/123 for more people having the same error.
