### ISSUE TITLE
Un-Handled exception after system upgrade

### ISSUE THREAD

**Issue by oldkingcone** [FrostyX/tracer#129]
Tracer:
 Call to Tracer API ended unexpectedly:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 45, in with_helpers
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 44, in <lambda>
    applications = filter(lambda app: app.helper, self)
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 217, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 120, in _helper
    if app.type == Applications.TYPES["DAEMON"]:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 202, in type
    elif self.is_session:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 194, in is_session
    if re.search('ssh-.*-session', str(self.name)):
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 271, in name
    if self.instances and bus.unit_path_from_pid(self.instances[0].pid):
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 261, in instances
    lambda process: self._attributes["name"] in [process.name(), process.real_name])
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 90, in filtered
    if function(process):
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 261, in <lambda>
    lambda process: self._attributes["name"] in [process.name(), process.real_name])
  File "/usr/lib/python3.7/site-packages/tracer/resources/processes.py", line 80, in name
    return 'ssh-{0}-session'.format(re.split(' |@',' '.join(self._attr("cmdline")))[1])
IndexError: list index out of range
```

**Comment by drmcnelson** [comment]
I see the same error.
