### ISSUE TITLE
Unexpected termination calling Tracer API, while using "dnf update".

### ISSUE THREAD

**Issue by Aspen-TWN** [FrostyX/tracer#140]
As title, the environment is on Fedora 31 Workstation.

Name         : python3-dnf-plugin-tracer
Version      : 4.0.10

Error message:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 34, in sorted
    self.replace_values(attribute, None, "")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 30, in replace_values
    app.update(attribute, required_value)
TypeError: update() takes 2 positional arguments but 3 were given

**Comment by FrostyX** [comment]
Thank you for the report.

I was trying to reproduce the issue but I wasn't successful.
Does it happen to you every time?
