### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by adatum** [FrostyX/tracer#148]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 45, in with_helpers
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 44, in <lambda>
    applications = filter(lambda app: app.helper, self)
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 217, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 120, in _helper
    if app.type == Applications.TYPES["DAEMON"]:
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 204, in type
    elif self.is_service:
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 212, in is_service
    return SystemdDbus().unit_path_from_id("{0}.service".format(self.name))
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 273, in name
    Id = bus.get_unit_property_from_pid(self.instances[0].pid,'Id')
IndexError: list index out of range

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

```

Happened during a `dnf upgrade`. 
dnf version 4.2.23
Fedora 32 5.6.15-300.fc32.x86_64

**Comment by manpreetszr** [comment]
Just ran into this on F34 dnf/4.7.0 .

```
% uname -a
Linux rrrrrrrr 5.11.20-300.fc34.x86_64 #1 SMP Wed May 12 15:45:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

% dnf --version
4.7.0
Installed: dnf-0:4.7.0-1.fc34.noarch at Sun 16 May 2021 06:47:11 PM GMT
Built    : Fedora Project at Thu 13 May 2021 02:35:13 PM GMT

Installed: rpm-0:4.16.1.3-1.fc34.x86_64 at Fri 23 Apr 2021 10:58:11 AM GMT
Built    : Fedora Project at Mon 22 Mar 2021 11:03:11 AM GMT
```
