### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by MichaelRiss** [FrostyX/tracer#151]
I see such errors on Fedora 31 when installing groups of packages on fairly fresh machines. Unfortunately, I'm not able to reproduce these errors reliably with a specific sequence of dnf commands. There seems to be a random factor involved.
But maybe the trace already highlights the problem.

```
Tracer:
 Call to Tracer API ended unexpectedly:
 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'NoneType' object is not callable
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
   {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'str' and 'NoneType'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

```

**Comment by FrostyX** [comment]
Hello @MichaelRiss,
thank you for reporting the issue.

> Unfortunately, I'm not able to reproduce these errors reliably with a specific sequence of dnf commands.
> There seems to be a random factor involved.

This is always unfortunate. If you figure out some reproducer please post it here. Meanwhile, I will try to reproduce the issue with tests. But reproducer would be great because otherwise, we can't be really sure if we fixed the issue or another one.

By the way, what Tracer version do you use?

**Comment by MichaelRiss** [comment]
I guessed so. That's something that I also saw with other tracer issues, when tracer is called from within dnf, it's often a matter of chance that a bug is triggered. Which is strange as dnf seems to be single threaded, so you would might think in the same conditions you will get the same execution sequence and therefore tracer will get called with the same arguments, but no.
And I'm testing automated installations with ansible, so to a large part every installation should be the same - minus changes in the Fedora update repositories. If I can nail down a bug-provoking sequence, I will of course post it here, but judging from the past, this might not be that easy.

I'm using these tracer packages on Fedora 31:
```
tracer-common-0.7.4-1.fc31.noarch
python3-dnf-plugin-tracer-4.0.10-1.fc31.noarch
python3-tracer-0.7.4-1.fc31.noarch
```

**Comment by FrostyX** [comment]
Leaving all the context alone, I was able to reproduce the issue 

	def test_application_sorted_none_helper(self):
		default_type = Applications.DEFAULT_TYPE
		a1 = Application({'name': 'foo', 'helper': None, 'type': default_type})
		a2 = Application({'name': 'baz', 'helper': 'qux', 'type': default_type})
		collection = ApplicationsCollection([a1, a2])
		collection.sorted('helper')

So if nothing else, I can make sure this test won't fail. But it doesn't make any sense to me because the failing line is

    self.args.applications.with_helpers().exclude_types(types).sorted("helper")

and the `with_helpers()` method selects only applications with non-`None` helpers, so I have no idea how the `None` value can then appear in the `sorted` method.

	def with_helpers(self):
		applications = filter(lambda app: app.helper, self)
		return ApplicationsCollection(applications)

**Comment by GabrielRavier** [comment]
I've had similar sporadic issues on Fedora too, though there is a difference in that I seem to get `str` instead of `NoneType` as the called type :

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by MichaelRiss** [comment]
Indeed, I also see those. This one is from Fedora 31.
```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.7/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
```

The difference to the one of @GabrielRavier is the python version, his is python3.8, mine is python3.7 - in case this is of interest.

**Comment by timjackson** [comment]
On Fedora 32 I saw the below. In this case, only a few packages were updated; does it possibly have something to do with nothing needing to be restarted?

Environment:
python3-3.8.5-5.fc32.x86_64
python3-dnf-plugin-tracer-4.0.10-2.fc32.noarch
python3-tracer-0.7.4-1.fc32.noarch
tracer-common-0.7.4-1.fc32.noarch

Output:
```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.8/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
  crun-0.14.1-5.fc32.x86_64              pcre2-10.35-6.fc32.i686                
  pcre2-10.35-6.fc32.x86_64              pcre2-syntax-10.35-6.fc32.noarch       
  pcre2-utf16-10.35-6.fc32.x86_64        pcre2-utf32-10.35-6.fc32.x86_64  
```

**Comment by GabrielRavier** [comment]
I just had to do the exact same upgrade (or at least pretty close, I upgraded all of these : `crun libvala libvala-devel pcre2 pcre2 pcre2-devel pcre2-syntax pcre2-utf16 pcre2-utf32 php-swaggest-json-schema python3-xapps-overrides rubygem-minitest steam vala xapps xapps-devel libxcrypt-compat`) and didn't get any error, so I think we can confirm this is very volatile

**Comment by MichaelRiss** [comment]
It still sporadically happens on Fedora 34:

```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer.render()
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 91, in render
    return view.render()
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
  glusterfs-9.2-1.fc34.x86_64                                                   
  glusterfs-cli-9.2-1.fc34.x86_64                                               
  glusterfs-client-xlators-9.2-1.fc34.x86_64                                    
  glusterfs-fuse-9.2-1.fc34.x86_64                                              
  libgfapi0-9.2-1.fc34.x86_64                                                   
  libgfrpc0-9.2-1.fc34.x86_64                                                   
  libgfxdr0-9.2-1.fc34.x86_64                                                   
  libglusterd0-9.2-1.fc34.x86_64                                                
  libglusterfs0-9.2-1.fc34.x86_64                                               
  libzstd-1.5.0-1.fc34.x86_64                                                   
  slack-4.16.0-0.1.fc21.x86_64                                                  
  systemd-248.3-1.fc34.x86_64                                                   
  systemd-container-248.3-1.fc34.x86_64                                         
  systemd-libs-248.3-1.fc34.x86_64                                              
  systemd-networkd-248.3-1.fc34.x86_64                                          
  systemd-oomd-defaults-248.3-1.fc34.x86_64                                     
  systemd-pam-248.3-1.fc34.x86_64                                               
  systemd-rpm-macros-248.3-1.fc34.noarch                                        
  systemd-udev-248.3-1.fc34.x86_64                                              
  xorg-x11-drv-nouveau-1:1.0.17-1.fc34.x86_64                                   
  zstd-1.5.0-1.fc34.x86_64                                                      

Complete!
```

The system is using the following tracer packages:

```
tracer-common-0.7.6-1.fc34.noarch
python3-tracer-0.7.6-1.fc34.noarch
python3-dnf-plugin-tracer-4.0.13-3.fc34.noarch
```

Considering the hypothesis of @timjackson, that the error only occurs when no services need restarting, at least in this case it looks like it does not apply as replacing `systemd` would definitely require a restart of services if not the whole system.
