### ISSUE TITLE
Call to Tracer API ended unexpectedly

### ISSUE THREAD

**Issue by thielmc** [FrostyX/tracer#156]
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer.render()
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 91, in render
    return view.render()
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

**Comment by johnsonjh** [comment]
Also had this, installing `DMD` on Fedora 33:

```
Dependencies resolved.
================================================================================
 Package              Arch        Version               Repository         Size
================================================================================
Installing:
 dmd                  x86_64      2.095.1-0             @commandline       14 M
Installing dependencies:
 glibc-devel          i686        2.32-4.fc33           updates           1.0 M
 libxcrypt-devel      i686        4.4.18-1.fc33         updates            29 k

Transaction Summary
================================================================================
Install  3 Packages

Total size: 15 M
Total download size: 1.1 M
Installed size: 199 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): libxcrypt-devel-4.4.18-1.fc33.i686.rpm    66 kB/s |  29 kB     00:00    
(2/2): glibc-devel-2.32-4.fc33.i686.rpm         912 kB/s | 1.0 MB     00:01    
--------------------------------------------------------------------------------
Total                                           678 kB/s | 1.1 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : libxcrypt-devel-4.4.18-1.fc33.i686                     1/3 
  Installing       : glibc-devel-2.32-4.fc33.i686                           2/3 
  Installing       : dmd-2.095.1-0.x86_64                                   3/3 
  Running scriptlet: dmd-2.095.1-0.x86_64                                   3/3 
  Verifying        : glibc-devel-2.32-4.fc33.i686                           1/3 
  Verifying        : libxcrypt-devel-4.4.18-1.fc33.i686                     2/3 
  Verifying        : dmd-2.095.1-0.x86_64                                   3/3 
New leaves:
  dmd.x86_64
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 36, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer.render()
  File "/usr/lib/python3.9/site-packages/dnf-plugins/tracer.py", line 91, in render
    return view.render()
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.9/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.9/site-packages/tracer/resources/collections.py", line 38, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Installed:
  dmd-2.095.1-0.x86_64                      glibc-devel-2.32-4.fc33.i686       
  libxcrypt-devel-4.4.18-1.fc33.i686       

Complete!
```

**Comment by tcitworld** [comment]
Had this exact issue on Fedora 34 as well. Using tracer `0.7.5`, and `4.0.13` of `python3-dnf-plugin-tracer`.

**Comment by pjoc** [comment]
Just got this on Fedora 34 while running 'dnf update'.

python3-tracer-0.7.6-1.fc34.noarch

**Comment by Conan-Kudo** [comment]
This is also happening in Mageia, see [mgabz#28577](https://bugs.mageia.org/show_bug.cgi?id=28577).

**Comment by FrostyX** [comment]
Thank you for the reports guys,
yet another occurrence seems to be reported here 
https://bugzilla.redhat.com/show_bug.cgi?id=1958779

I am planning to do some Tracer bugfixing the following week and make a new release.
