### ISSUE TITLE
Call to Tracer API ended unexpectedly

### ISSUE THREAD

**Issue by jemadsen2** [FrostyX/tracer#190]
I received this traceback after executing:
`dnf upgrade -y --exclude="cdda2wav cdrecord mkisofs schily-libs"`
I had to skip the packages because the "rpm is not signed"
```
  Verifying        : kernel-modules-extra-5.18.19-100.fc35.x86_64                                                  144/144 
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dnf-plugins/tracer.py", line 66, in transaction
    tracer.render()
  File "/usr/lib/python3.10/site-packages/dnf-plugins/tracer.py", line 91, in render
    return view.render()
  File "/usr/lib/python3.10/site-packages/tracer/views/default.py", line 76, in render
    {"title": "  * " + _("These applications manually:"), "content": without_helpers_content()},
  File "/usr/lib/python3.10/site-packages/tracer/views/default.py", line 35, in without_helpers_content
    .exclude_types(Applications.TYPES["ERASED"])
  File "/usr/lib/python3.10/site-packages/tracer/resources/collections.py", line 75, in exclude_types
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.10/site-packages/tracer/resources/collections.py", line 74, in <lambda>
    applications = filter(lambda app: app.type not in app_types, self)
  File "/usr/lib/python3.10/site-packages/tracer/resources/applications.py", line 213, in type
    elif self.is_session:
  File "/usr/lib/python3.10/site-packages/tracer/resources/applications.py", line 205, in is_session
    if re.search('ssh-.*-session', str(self.name)):
  File "/usr/lib/python3.10/site-packages/tracer/resources/applications.py", line 300, in name
    if self.is_interpreted:
  File "/usr/lib/python3.10/site-packages/tracer/resources/applications.py", line 201, in is_interpreted
    return self.instances and self.instances[0].is_interpreted
IndexError: list index out of range

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
```
I hope this is useful,
Jens

**Comment by buckaroogeek** [comment]
I received Call to Trace API ended unexpectedly. Different dnf. I was running dnf on F39 in a vagrant vm.

```
sudo dnf install crun
```

```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dnf-plugins/tracer.py", line 65, in transaction
    tracer = TracerFacade(packages)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dnf-plugins/tracer.py", line 78, in __init__
    self.apps = self.get_apps(packages)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dnf-plugins/tracer.py", line 83, in get_apps
    return query.from_packages(packages).now().affected_applications().get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tracer/query.py", line 72, in get
    return self._method(**self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tracer/resources/tracer.py", line 99, in trace_affected
    for file in self._PACKAGE_MANAGER.package_files(package.name):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tracer/resources/PackageManager.py", line 55, in package_files
    return self.package_managers[0].package_files(pkg_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tracer/packageManagers/dnf.py", line 52, in package_files
    return super(Dnf, self).package_files(pkg_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tracer/packageManagers/rpm.py", line 105, in package_files
    fi = rpm.fi(next(mi))
         ^^^^^^
AttributeError: module 'rpm' has no attribute 'fi'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Installed:
  criu-libs-3.19-2.fc39.x86_64                                             crun-1.12-1.fc39.x86_64                                             yajl-2.1.0-22.fc39.x86_64                                            
```
