### ISSUE TITLE
TypeError: a float is required

### ISSUE THREAD

**Issue by ignatenkobrain** [FrostyX/tracer#28]
```python
$ sudo tracer --show-resource=processes
Swipe your right index finger across the fingerprint reader
PID       Time running        User                Process   
----------------------------------------------------------------------------------------------------
sudoTraceback (most recent call last):
  File "/bin/tracer", line 34, in <module>
    tracer.main.run()
  File "/usr/lib/python2.7/site-packages/tracer/main.py", line 42, in run
    return router.dispatch()
  File "/usr/lib/python2.7/site-packages/tracer/resources/router.py", line 51, in dispatch
    controller.render()
  File "/usr/lib/python2.7/site-packages/tracer/controllers/resource.py", line 47, in render
    if   r == 'processes':    self.render_processes()
  File "/usr/lib/python2.7/site-packages/tracer/controllers/resource.py", line 56, in render_processes
    view.render()
  File "/usr/lib/python2.7/site-packages/tracer/views/resource/processes.py", line 10, in render
    print line.format(process.pid, process.str_started_ago, process.username, process.name)
  File "/usr/lib/python2.7/site-packages/tracer/resources/processes.py", line 96, in str_started_ago
    started = datetime.datetime.fromtimestamp(self.create_time)
TypeError: a float is required
```

**Comment by FrostyX** [comment]
Fixed by 728edc64a22bc9c1ec0171af9dc715b25dfc2444
