### ISSUE TITLE
Traceback due to missing process

### ISSUE THREAD

**Issue by seanmil** [FrostyX/tracer#43]
I received this traceback during a dnf run. Thanks!

Traceback (most recent call last):
  File "/bin/tracer", line 34, in <module>
    tracer.main.run()
  File "/usr/lib/python2.7/site-packages/tracer/main.py", line 42, in run
    return router.dispatch()
  File "/usr/lib/python2.7/site-packages/tracer/resources/router.py", line 55, in dispatch
    controller = DefaultController(self.args, self.packages)
  File "/usr/lib/python2.7/site-packages/tracer/controllers/default.py", line 61, in __init__
    self.applications = self.tracer.trace_affected(self._user(args.user))
  File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 107, in trace_affected
    p = self._apply_rules(p)
  File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 120, in _apply_rules
    parent = process.parent()
  File "/usr/lib/python2.7/site-packages/tracer/resources/processes.py", line 142, in parent
    if self.ppid():
  File "/usr/lib/python2.7/site-packages/tracer/resources/processes.py", line 76, in ppid
    return self._attr("ppid")
  File "/usr/lib/python2.7/site-packages/tracer/resources/processes.py", line 93, in _attr
    try: return attr()
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 480, in ppid
    return self._proc.ppid()
  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 706, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=24685)

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
Complete!

**Comment by FrostyX** [comment]
Hello @seanmil,
thank you for the feedback.

I thought that the issue was already fixed. Well, another try with 75744df :-) I am releasing the version `0.6.4` for Fedora and closing this. Please feel free to reopen the issue if you experience it even on new version.
