### ISSUE TITLE
Error during documentation generation at build

### ISSUE THREAD

**Issue by Conan-Kudo** [FrostyX/tracer#48]
After fixing the build-time dependencies in #47, I got the following errors on the documentation generation (note that the build succeeds despite this, but it would be *really* good if it didn't fail anymore).

```
[  406s] sphinx-build -b man -d build/doctrees   source build/man
[  408s] Running Sphinx v1.3.1
[  408s] making output directory...
[  408s] loading pickled environment... not yet created
[  408s] building [mo]: targets for 0 po files that are out of date
[  408s] building [man]: all manpages
[  408s] updating environment: 6 added, 0 changed, 0 removed
[  408s] reading sources... [ 16%] api
[  408s] reading sources... [ 33%] developer-guide
[  408s] reading sources... [ 50%] get-tracer
[  408s] reading sources... [ 66%] index
[  408s] reading sources... [ 83%] manpage
[  408s] reading sources... [100%] user-guide
[  408s] 
[  408s] /home/abuild/rpmbuild/BUILD/tracer-git/doc/source/api.rst:13: WARNING: autodoc: failed to import class u'Query' from module u'tracer.query'; the following exception was raised:
[  408s] Traceback (most recent call last):
[  408s]   File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
[  408s]     __import__(self.modname)
[  408s]   File "/home/abuild/rpmbuild/BUILD/tracer-git/tracer/query.py", line 19, in <module>
[  408s]     from tracer.resources.tracer import Tracer
[  408s]   File "/home/abuild/rpmbuild/BUILD/tracer-git/tracer/resources/tracer.py", line 27, in <module>
[  408s]     from tracer.resources.applications import Applications
[  408s]   File "/home/abuild/rpmbuild/BUILD/tracer-git/tracer/resources/applications.py", line 21, in <module>
[  408s]     from bs4 import BeautifulSoup, element
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
[  408s]     from .builder import builder_registry, ParserRejectedMarkup
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/builder/__init__.py", line 4, in <module>
[  408s]     from bs4.element import (
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/element.py", line 8, in <module>
[  408s]     from bs4.dammit import EntitySubstitution
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/dammit.py", line 13, in <module>
[  408s]     from html.entities import codepoint2name
[  408s] ImportError: No module named html.entities
[  408s] /home/abuild/rpmbuild/BUILD/tracer-git/doc/source/api.rst:46: WARNING: autodoc: failed to import class u'Application' from module u'tracer.resources.applications'; the following exception was raised:
[  408s] Traceback (most recent call last):
[  408s]   File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
[  408s]     __import__(self.modname)
[  408s]   File "/home/abuild/rpmbuild/BUILD/tracer-git/tracer/resources/applications.py", line 21, in <module>
[  408s]     from bs4 import BeautifulSoup, element
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
[  408s]     from .builder import builder_registry, ParserRejectedMarkup
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/builder/__init__.py", line 4, in <module>
[  408s]     from bs4.element import (
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/element.py", line 8, in <module>
[  408s]     from bs4.dammit import EntitySubstitution
[  408s]   File "/usr/lib/python2.7/site-packages/bs4/dammit.py", line 13, in <module>
[  408s]     from html.entities import codepoint2name
[  408s] ImportError: No module named html.entities
[  408s] looking for now-outdated files... none found
[  408s] pickling environment... done
[  408s] checking consistency... done
[  408s] writing... tracer.8 { } 
[  408s] build succeeded, 2 warnings.
[  409s] 
[  409s] Build finished. The manual pages are in build/man.
```

However, if I switch tracer to build with Python 3 (and thus switch all the BuildRequires and Requires to their Python 3 counterparts), this goes away and everything generates cleanly. Now this is great if you're using Python 3, but tracer currently is set up as a Python 2 application. 

It would be great if this worked properly even on Python 2, if it was within your power.

**Comment by FrostyX** [comment]
Hello @Conan-Kudo, thank you for the feedback.

Based on #47 I suppose, that you have `python-beautifulsoup4` installed. Can you please tell me which version do you have?

You should get that error even from `python -c "from bs4 import BeautifulSoup, element"`, because it does `from html.entities import codepoint2name`. On my computer the import looks like `from htmlentitydefs import codepoint2name` and it works. I will try to install your version and examine it.

**Comment by Conan-Kudo** [comment]
@FrostyX I think I figured out what's wrong, and I'm going to test and see if it fixes it. It might be an error in where 2to3 is being run in the building of the `python-beautifulsoup4` package.

**Comment by Conan-Kudo** [comment]
@FrostyX I managed to fix the issue by fixing the `python-beautifulsoup4` package in Mageia. It was an issue in that package, and I corrected it. So this is not an issue anymore.

**Comment by FrostyX** [comment]
Ok @Conan-Kudo,
Thank you for the resolution.
