### ISSUE TITLE
Traceback report: list index out of range

### ISSUE THREAD

**Issue by xasx** [FrostyX/tracer#75]
I encountered a traceback with the dnf tracer plugin, here's the error message
```
b'Traceback (most recent call last):
  File "/bin/tracer", line 34, in <module>
    tracer.main.run()
  File "/usr/lib/python3.5/site-packages/tracer/main.py", line 45, in run
    return router.dispatch()
  File "/usr/lib/python3.5/site-packages/tracer/resources/router.py", line 58, in dispatch
    controller.render()
  File "/usr/lib/python3.5/site-packages/tracer/controllers/default.py", line 71, in render
    view.render()
  File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 60, in render
    {"title": "  * " + _("These applications manually:"), "content": without_helpers_content()},
  File "/usr/lib/python3.5/site-packages/tracer/views/default.py", line 30, in without_helpers_content
    apps = self.args.applications.exclude_types(Applications.TYPES["ERASED"]).without_helpers().sorted("name")
  File "/usr/lib/python3.5/site-packages/tracer/resources/collections.py", line 42, in without_helpers
    return ApplicationsCollection(applications)
  File "/usr/lib/python3.5/site-packages/tracer/resources/collections.py", line 41, in <lambda>
    applications = filter(lambda app: not app.helper, self)
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 201, in helper
    helper = self._attributes["helper"] if self._attributes["helper"] else Applications._helper(self)
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 118, in _helper
    if app.type == Applications.TYPES["DAEMON"]:
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 192, in type
    return Applications.TYPES["DAEMON"] if self.has_service_file else self._attributes["type"]
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 196, in has_service_file
    return os.path.isfile("/usr/lib/systemd/system/{0}.service".format(self.name))
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 252, in name
    if self.is_interpreted:
  File "/usr/lib/python3.5/site-packages/tracer/resources/applications.py", line 188, in is_interpreted
    return self.instances and self.instances[0].is_interpreted
IndexError: list index out of range
'
Bitte besuchen Siehttps://github.com/FrostyX/tracer/issues and submit the issue. Thank you
Wir bitten, die Unannehmlichkeiten zu entschuldigen
```
(\n -> line break replaced)

Unfortunately, I cannot track down the cause of this.

**Comment by FrostyX** [comment]
Hello @xasx, thank you for the feedback 

This is interesting for me

    return self.instances and self.instances[0].is_interpreted

Why would it even check `self.instances[0]` when `bool(self.instances)` is `False`. I am gonna look at it.
