### ISSUE TITLE
dnf tracer traceback report

### ISSUE THREAD

**Issue by xasx** [FrostyX/tracer#89]
Today dnf's tracer plugin failed with the following traceback:

```
error: db5 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
error: cannot open Packages index using db5 -  (-30969)
error: cannot open Packages database in /var/lib/rpm
Traceback (most recent call last):
  File "/bin/tracer", line 34, in <module>
    tracer.main.run()
  File "/usr/lib/python3.5/site-packages/tracer/main.py", line 45, in run
    return router.dispatch()
  File "/usr/lib/python3.5/site-packages/tracer/resources/router.py", line 52, in dispatch
    controller = DefaultController(self.args, self.packages)
  File "/usr/lib/python3.5/site-packages/tracer/controllers/default.py", line 62, in __init__
    self.applications = self.tracer.trace_affected(self._user(args.user))
  File "/usr/lib/python3.5/site-packages/tracer/resources/tracer.py", line 96, in trace_affected
    for file in self._PACKAGE_MANAGER.package_files(package.name):
  File "/usr/lib/python3.5/site-packages/tracer/resources/PackageManager.py", line 55, in package_files
    return self.package_managers[0].package_files(pkg_name)
  File "/usr/lib/python3.5/site-packages/tracer/packageManagers/dnf.py", line 34, in package_files
    if self._is_installed(pkg_name):
  File "/usr/lib/python3.5/site-packages/tracer/packageManagers/rpm.py", line 151, in _is_installed
    mi = ts.dbMatch('name', pkg_name)
_rpm.error: rpmdb open failed
```

Whereas

```bash
$ sudo tracer
```

does not bring such an error.

Maybe a concurrency issue? Or might it have to do with the packages upgraded? These were upgraded:

```
  GraphicsMagick.x86_64 1.3.26-1.fc25               expat.i686 2.2.1-1.fc25                              expat.x86_64 2.2.1-1.fc25                             
  expat-devel.x86_64 2.2.1-1.fc25                   fwupd.x86_64 0.9.5-1.fc25                            fwupd-labels.x86_64 0.9.5-1.fc25                      
  glibc.i686 2.24-9.fc25                            glibc.x86_64 2.24-9.fc25                             glibc-common.x86_64 2.24-9.fc25                       
  glibc-devel.x86_64 2.24-9.fc25                    glibc-headers.x86_64 2.24-9.fc25                     glibc-langpack-en.x86_64 2.24-9.fc25                  
  jsoncpp.x86_64 1.8.1-3.fc25                       kernel-headers.x86_64 4.11.9-200.fc25                libcrypt-nss.i686 2.24-9.fc25                         
  libcrypt-nss.x86_64 2.24-9.fc25                   libdb.i686 5.3.28-24.fc25                            libdb.x86_64 5.3.28-24.fc25                           
  libdb-devel.x86_64 5.3.28-24.fc25                 libdb-utils.x86_64 5.3.28-24.fc25                    libdfu.x86_64 0.9.5-1.fc25                            
  libguestfs.x86_64 1:1.36.5-1.fc25                 libguestfs-tools-c.x86_64 1:1.36.5-1.fc25            libguestfs-xfs.x86_64 1:1.36.5-1.fc25                 
  libsndfile.i686 1.0.28-3.fc25                     libsndfile.x86_64 1.0.28-3.fc25                      nautilus-sendto.x86_64 1:3.8.5-1.fc25                 
  nodejs.x86_64 2:8.1.4-1nodesource.fc25            pcre.i686 8.41-1.fc25                                pcre.x86_64 8.41-1.fc25                               
  pcre-cpp.x86_64 8.41-1.fc25                       pcre-devel.x86_64 8.41-1.fc25                        pcre-utf16.x86_64 8.41-1.fc25                         
  pcre-utf32.x86_64 8.41-1.fc25                     perf.x86_64 4.11.9-200.fc25                          perl-Scalar-List-Utils.x86_64 3:1.48-1.fc25           
  python2-rpkg.noarch 1.49-5.fc25                   qt5-qtwebengine.x86_64 5.9.0-4.fc25                  spandsp.x86_64 0.0.6-3.fc25                           
  xen-libs.x86_64 4.7.2-7.fc25                      xen-licenses.x86_64 4.7.2-7.fc25                    

```

**Comment by ferdnyc** [comment]
I just encountered an identical error (right down to the line numbers in the traceback), also while updating the `glibc` RPMs (and _only_ the `glibc` RPMs, significantly), so that sounds like the common thread.

Specifically, this was the following chain:
```
python3-dnf-plugins-extras-tracer-0.0.12-4.fc25.noarch
python3-tracer-0.6.12-4.fc25.noarch
dnf-1.1.10-6.fc25.noarch
rpm-4.13.0.1-2.fc25.x86_64
```
updating the following package set:
```
================================================================================
 Package                 Arch         Version               Repository     Size
================================================================================
Upgrading:
 glibc                   i686         2.24-10.fc25          updates       4.0 M
 glibc                   x86_64       2.24-10.fc25          updates       3.3 M
 glibc-common            x86_64       2.24-10.fc25          updates       880 k
 glibc-devel             x86_64       2.24-10.fc25          updates       937 k
 glibc-headers           x86_64       2.24-10.fc25          updates       501 k
 glibc-langpack-en       x86_64       2.24-10.fc25          updates       282 k
 libcrypt-nss            i686         2.24-10.fc25          updates        44 k
 libcrypt-nss            x86_64       2.24-10.fc25          updates        45 k

Transaction Summary
================================================================================
Upgrade  8 Packages
```

**Comment by sean797** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1465809#c5 has an explanation of what I think is going on, closing this based on that and F25 being EOL, please re-open if you hit this issue again.

**Comment by ferdnyc** [comment]
I don't think I've seen this happen since; 6+ months between incidents makes it seem pretty low-impact.
