### ISSUE TITLE
IndexError: list index out of range in ProcessWrapper

### ISSUE THREAD

**Issue by gsauthof** [FrostyX/tracer#95]
Got this on a regularly updated CentOS 7 system:

    Traceback (most recent call last):
      File "/bin/tracer", line 34, in <module>
        tracer.main.run()
      File "/usr/lib/python2.7/site-packages/tracer/main.py", line 45, in run
        return router.dispatch()
      File "/usr/lib/python2.7/site-packages/tracer/resources/router.py", line 58, in dispatch
        controller.render()
      File "/usr/lib/python2.7/site-packages/tracer/controllers/default.py", line 71, in render
        view.render()
      File "/usr/lib/python2.7/site-packages/tracer/views/default.py", line 74, in render
        blocks.append({"content": note_content()})
      File "/usr/lib/python2.7/site-packages/tracer/views/default.py", line 54, in note_content
        view.assign("static_count", self.args.applications.count_type(Applications.TYPES["STATIC"]))
      File "/usr/lib/python2.7/site-packages/tracer/resources/collections.py", line 57, in count_type
        if application.type == app_type:
      File "/usr/lib/python2.7/site-packages/tracer/resources/applications.py", line 202, in type
        elif self.is_session:
      File "/usr/lib/python2.7/site-packages/tracer/resources/applications.py", line 196, in is_session
        return self.instances and self.instances[0].is_session
      File "/usr/lib/python2.7/site-packages/tracer/resources/applications.py", line 260, in instances
        lambda process: self._attributes["name"] in [process.name(), process.real_name])
      File "/usr/lib/python2.7/site-packages/tracer/resources/collections.py", line 83, in filtered
        if function(process):
      File "/usr/lib/python2.7/site-packages/tracer/resources/applications.py", line 260, in <lambda>
        lambda process: self._attributes["name"] in [process.name(), process.real_name])
      File "/usr/lib/python2.7/site-packages/tracer/resources/processes.py", line 73, in name
        return 'ssh-{0}-session'.format(re.split(' |@|',self._attr("cmdline")[0])[1])
    IndexError: list index out of range

Using the tracer package from EPEL (python2-tracer-0.6.13-2.el7.noarch).

**Comment by FrostyX** [comment]
@gsauthof can you please confirm that 0ac3842 fixes your issue?

**Comment by gsauthof** [comment]
It's kind of hard to reproduce this issue. Even before your fix.

However, haven't run into it again, so far.
