### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ohhai** [FrostyX/tracer#98]
Had this error after "dnf update" operation in Fedora 27 x64, python3-dnf-plugin-tracer-2.0.5-1.fc27.noarch

```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 22, in with_helpers_content
    helpers = "; ".join(application.helpers)
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 241, in helpers
    if not self.helper_contains_formating:
  File "/usr/lib/python3.6/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
    return bool(re.search("\{.*\}", self.helper))
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by ohhai** [comment]
Note: python3-dnf-plugin-tracer was updated as well, previous version was 2.0.4-1.fc27

**Comment by abitrolly** [comment]
Just got the same trace here with dnf-plugins-extras-2.0.5-1.fc27.src.rpm

**Comment by hamburger1984** [comment]
I got (almost) the same error in fedora 29.

```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 23, in with_helpers_content
    if application.helper_contains_formating and not application.helper_contains_name:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
    return bool(re.search("\{.*\}", self.helper))
  File "/usr/lib64/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```
