### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by agross** [FrostyX/tracer#99]
```
$ dnf update -y
...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 29, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 31, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
```

**Comment by xasx** [comment]
Running `sudo tracer` after the `dnf` works, though (taking a very long time).

**Comment by FrostyX** [comment]
I have difficulties with reproducing this issue. Does this happen all the time?

**Comment by xasx** [comment]
Not for me, this seems to be a one-time-thingy.

**Comment by franklinyu** [comment]
I think I have a slightly different traceback:

```text
/usr/lib64/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)

Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 29, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 31, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

after that `sudo tracer` gives the correct output, along with a warning:

```text
/usr/lib64/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)
```

**Comment by angystardust** [comment]
Same issue here after upgrading (91 packages) my f27:

```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 29, in sorted
    return sorted(self, key=methodcaller(attribute))
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.6/site-packages/tracer/views/default.py", line 20, in with_helpers_content
    applications = self.args.applications.with_helpers().exclude_types(types).sorted("helper")
  File "/usr/lib/python3.6/site-packages/tracer/resources/collections.py", line 31, in sorted
    return sorted(self, key=attrgetter(attribute))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience
```
